# Site settings
title: My Journey Into a New Career 
header-img: img/home-bg.png
email: parsamoshiri5@gmail.com
copyright_name: pmo55
description: > # this means to ignore newlines until "baseurl:"
  Parsa's Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pmo55
learn_profile: pmo55
email_username: parsamoshiri5@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
